In [1]:
import os
from dotenv import load_dotenv
from google import genai

load_dotenv("../.env")

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError(
        "API key not found. Check your .env file."
    )

client = genai.Client(api_key=api_key)

print("Gemini client initialized successfully!")

ModuleNotFoundError: No module named 'dotenv'

In [2]:
import sys

print(sys.executable)

c:\Users\jhabh\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [1]:
%pip install python-dotenv google-genai

Requirement already satisfied: python-dotenv in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (1.2.4)
Requirement already satisfied: google-genai in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (2.29.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (4.15.1)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.61.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (2.14.0)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (16.1.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.20)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (50.0.2)
Requirement already satisfied: certifi in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.50.0)
Requirement already satisfied: typing-inspection>=0.4.4 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.8.0)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.1.1)
Requirement already satisfied: pycparser in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (3.11)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\.venv\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from dotenv import load_dotenv
from google import genai

print("All libraries imported successfully!")

All libraries imported successfully!

In [3]:
import os
from pathlib import Path
from dotenv import load_dotenv
from google import genai

# Find the .env file in the project folder
env_path = Path.cwd().resolve().parent / ".env"

load_dotenv(env_path)

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("API key not found. Check your .env file.")

client = genai.Client(api_key=api_key)

print("Gemini client initialized successfully!")

Gemini client initialized successfully!

In [4]:
models = client.models.list()

available_models = []

for model in models:
    name = model.name or ""

    if "generateContent" in (model.supported_actions or []):
        available_models.append(name)

print("Models available for text generation:")

for model in available_models:
    print(model)

Models available for text generation:
models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.1-flash-lite-image
models/gemini-nano-banana-2.1
models/gemini-3.5-flash
models/gemini-3.5-flash-lite
models/gemini-omni-flash-preview
models/gemini-omni-1.1-flash
models/gemini-3.5-transcribe
models/gemini-3.6-flash
models/gemini-3.7-flash
models/gemini-3.8-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/lyria-3.5
models/gemini-3.1-flash-tts-preview
models/gemini-3.8-flash-tts
models/gemini-3.8-flash-lite-tts
models/gemini-robotics-er-2-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/antigravity-preview-09-2026
models/antigravity-preview-latest
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025

In [6]:
import time
from google import genai

# Select the model for our experiment
MODEL_NAME = "gemini-3.8-flash"

# The question we want to test
question = """
A shopkeeper buys an item for ₹800 and sells it for ₹1000.
Calculate the profit percentage.
"""

# Method A: Direct-answer prompting
direct_prompt = f"""
Solve the following question.
Provide only the final answer.

Question: {question}
"""

# Method B: Structured reasoning prompting
structured_prompt = f"""
Solve the following question using a structured approach.
Identify the relevant quantities, perform the calculations,
verify the result, and provide the final answer.

Question: {question}
"""

# Run Method A
start_time = time.perf_counter()

direct_response = client.models.generate_content(
    model=MODEL_NAME,
    contents=direct_prompt
)

direct_time = time.perf_counter() - start_time

# Run Method B
start_time = time.perf_counter()

structured_response = client.models.generate_content(
    model=MODEL_NAME,
    contents=structured_prompt
)

structured_time = time.perf_counter() - start_time

# Display the results
print("===== DIRECT ANSWER =====")
print(direct_response.text)
print(f"Response time: {direct_time:.2f} seconds")

print("\n===== STRUCTURED REASONING =====")
print(structured_response.text)
print(f"Response time: {structured_time:.2f} seconds")

===== DIRECT ANSWER =====
25%
Response time: 2.78 seconds

===== STRUCTURED REASONING =====
Here is the step-by-step solution to the problem:

### **1. Identify the Relevant Quantities**
* **Cost Price ($CP$):** The price at which the item was bought = ₹800
* **Selling Price ($SP$):** The price at which the item was sold = ₹1000

---

### **2. Perform the Calculations**

* **Step A: Calculate the Profit**
  $$\text{Profit} = SP - CP$$
  $$\text{Profit} = 1000 - 800 = ₹200$$

* **Step B: Calculate the Profit Percentage**
  $$\text{Profit Percentage} = \left(\frac{\text{Profit}}{CP}\right) \times 100$$
  $$\text{Profit Percentage} = \left(\frac{200}{800}\right) \times 100$$
  $$\text{Profit Percentage} = \frac{1}{4} \times 100 = 25\%$$

---

### **3. Verify the Result**
* Calculate $25\%$ of the Cost Price ($₹800$):
  $$25\% \text{ of } 800 = 0.25 \times 800 = ₹200$$
* Add the profit to the Cost Price to check if it equals the Selling Price:
  $$\text{Selling Price} = CP + \text{Profit} = 800 + 200 = ₹1000$$
The calculated selling price matches the given selling price, confirming the result is correct.

---

### **4. Final Answer**
The profit percentage is **25%**.
Response time: 5.52 seconds

In [7]:
import time
import pandas as pd
from pathlib import Path

# Use the model that worked previously
MODEL_NAME = "gemini-3.8-flash"

# Our test question
question = (
    "A shopkeeper buys an item for ₹800 and sells it for ₹1000. "
    "Calculate the profit percentage."
)

# Define the two prompting methods
prompts = {
    "Direct": f"""
Solve the following question.
Provide only the final answer.

Question: {question}
""",

    "Structured": f"""
Solve the following question using a structured approach.
Identify the relevant quantities, perform the calculations,
verify the result, and provide the final answer.

Question: {question}
"""
}

# Run both methods and collect results
results = []

for method, prompt in prompts.items():

    print(f"Running {method} prompting...")

    start_time = time.perf_counter()

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt
    )

    elapsed_time = time.perf_counter() - start_time

    answer = response.text or ""

    # Get token usage when provided by the API
    usage = response.usage_metadata

    input_tokens = (
        getattr(usage, "prompt_token_count", None)
        if usage else None
    )

    output_tokens = (
        getattr(usage, "candidates_token_count", None)
        if usage else None
    )

    results.append({
        "question_id": "Q001",
        "category": "Mathematics",
        "difficulty": "Easy",
        "method": method,
        "question": question,
        "response": answer,
        "response_time_seconds": round(elapsed_time, 3),
        "input_tokens": input_tokens,
        "output_tokens": output_tokens
    })

# Display results
results_df = pd.DataFrame(results)

display(results_df)

Running Direct prompting...
Running Structured prompting...

,question_id,category,difficulty,method,question,response,response_time_seconds,input_tokens,output_tokens
0,Q001,Mathematics,Easy,Direct,A shopkeeper buys an item for ₹800 and sells i...,25%,145.683,44,3
1,Q001,Mathematics,Easy,Structured,A shopkeeper buys an item for ₹800 and sells i...,Here is the step-by-step solution using the st...,3.867,62,354

In [8]:
# Find the project folder
project_dir = Path.cwd().resolve().parent

# Create the results directory if necessary
results_dir = project_dir / "results"
results_dir.mkdir(parents=True, exist_ok=True)

# Save the experiment
output_path = results_dir / "pilot_results.csv"

results_df.to_csv(output_path, index=False)

print("Pilot experiment saved successfully!")
print(f"File location: {output_path}")

Pilot experiment saved successfully!
File location: C:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\results\pilot_results.csv

In [9]:
print(results_df[[
    "method",
    "response_time_seconds",
    "input_tokens",
    "output_tokens"
]])

       method  response_time_seconds  input_tokens  output_tokens
0      Direct                145.683            44              3
1  Structured                  3.867            62            354

In [10]:
import pandas as pd
from pathlib import Path

# Locate the project directory
project_dir = Path.cwd().resolve().parent

# Locate the dataset
dataset_path = project_dir / "data" / "questions.csv"

# Load the CSV
questions_df = pd.read_csv(dataset_path)

# Display the dataset
display(questions_df)

,id,category,difficulty,question,correct_answer
0,Q001,Mathematics,Easy,What is 15 percent of 200?,30
1,Q002,Mathematics,Medium,An item costs 800 rupees and sells for 1000 ru...,25%
2,Q003,Mathematics,Hard,A number is increased by 20 percent and then d...,4% decrease
3,Q004,Logical,Easy,"A is taller than B, and B is taller than C. Wh...",C
4,Q005,Logical,Medium,All roses are flowers. No flowers are made of ...,No
5,Q006,Logical,Hard,Exactly one of A and B is telling the truth. A...,Yes
6,Q007,Aptitude,Easy,A vehicle travels 150 km in 3 hours at a const...,50 km/h
7,Q008,Aptitude,Medium,A can complete a job in 6 days and B can compl...,2 days
8,Q009,Aptitude,Hard,A 30-litre mixture contains 40 percent milk. H...,6 litres
9,Q010,Algorithms,Easy,Which data structure follows the Last In First...,Stack
10,Q011,Algorithms,Medium,"Two nested loops each execute n times, and the...",O(n^2)
11,Q012,Algorithms,Hard,What is the worst-case time complexity of bina...,O(log n)

In [11]:
# Check the dataset dimensions
print("Dataset shape:", questions_df.shape)

# Check the column names
print("\nColumns:")
print(questions_df.columns.tolist())

# Count questions in each category
print("\nQuestions by category:")
print(questions_df["category"].value_counts())

# Count questions by difficulty
print("\nQuestions by difficulty:")
print(questions_df["difficulty"].value_counts())

# Check for missing values
print("\nMissing values:")
print(questions_df.isnull().sum())

# Check for duplicate question IDs
print("\nDuplicate IDs:", questions_df["id"].duplicated().sum())

Dataset shape: (12, 5)

Columns:
['id', 'category', 'difficulty', 'question', 'correct_answer']

Questions by category:
category
Mathematics    3
Logical        3
Aptitude       3
Algorithms     3
Name: count, dtype: int64

Questions by difficulty:
difficulty
Easy      4
Medium    4
Hard      4
Name: count, dtype: int64

Missing values:
id                0
category          0
difficulty        0
question          0
correct_answer    0
dtype: int64

Duplicate IDs: 0

In [13]:
import os
import sys
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv
from google import genai

# Locate the project directory
project_dir = Path.cwd().resolve().parent

# Add the project directory to Python's search path
sys.path.insert(0, str(project_dir))

# Now import the function from model.py
from src.model import generate_response

print("Project directory:", project_dir)
print("Model imported successfully!")


# Load the API key
load_dotenv(project_dir / ".env")

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("API key not found. Check your .env file.")

# Initialize Gemini
client = genai.Client(api_key=api_key)

# Load the dataset
dataset_path = project_dir / "data" / "questions.csv"
questions_df = pd.read_csv(dataset_path)

# Store experiment results
experiment_results = []

# Run both prompting methods on every question
for _, row in questions_df.iterrows():

    question_id = row["id"]
    question = row["question"]

    for method in ["Direct", "Structured"]:

        print(f"Question: {question_id} | Method: {method}")

        result = generate_response(
            client=client,
            question=question,
            method=method
        )

        experiment_results.append({
            "id": question_id,
            "category": row["category"],
            "difficulty": row["difficulty"],
            "method": method,
            "question": question,
            "correct_answer": row["correct_answer"],
            "response": result["response"],
            "response_time_seconds": result["response_time_seconds"],
            "input_tokens": result["input_tokens"],
            "output_tokens": result["output_tokens"]
        })

# Convert the results into a DataFrame
results_df = pd.DataFrame(experiment_results)

display(results_df.head())

Project directory: C:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment
Model imported successfully!
Question: Q001 | Method: Direct

ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

In [14]:
import importlib
import src.model

importlib.reload(src.model)

from src.model import generate_response

print("Updated generate_response function loaded!")

Updated generate_response function loaded!

In [15]:
test_question = "What is 15 percent of 200?"

test_result = generate_response(
    client=client,
    question=test_question,
    method="Direct"
)

print("Response:", test_result["response"])
print("Response time:", test_result["response_time_seconds"], "seconds")
print("Input tokens:", test_result["input_tokens"])
print("Output tokens:", test_result["output_tokens"])

Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Response: 30
Response time: 4.135 seconds
Input tokens: 30
Output tokens: 2

In [16]:
import importlib
import src.model

importlib.reload(src.model)

from src.model import generate_response

print("Updated function loaded successfully!")

Updated function loaded successfully!

In [17]:
test_result = generate_response(
    client=client,
    question="What is 15 percent of 200?",
    method="Direct"
)

print("Response:", test_result["response"])
print(
    "Successful request time:",
    test_result["response_time_seconds"],
    "seconds"
)
print(
    "Total elapsed time:",
    test_result["total_elapsed_seconds"],
    "seconds"
)
print("Input tokens:", test_result["input_tokens"])
print("Output tokens:", test_result["output_tokens"])

Response: 30
Successful request time: 5.764 seconds
Total elapsed time: 5.764 seconds
Input tokens: 30
Output tokens: 2

In [18]:
print("Response:", test_result["response"])
print("Successful request time:", test_result["response_time_seconds"], "seconds")
print("Total elapsed time:", test_result["total_elapsed_seconds"], "seconds")
print("Input tokens:", test_result["input_tokens"])
print("Output tokens:", test_result["output_tokens"])

Response: 30
Successful request time: 5.764 seconds
Total elapsed time: 5.764 seconds
Input tokens: 30
Output tokens: 2

In [19]:
# Reload the updated dataset
questions_df = pd.read_csv(dataset_path)

# Check the number of questions
print("Total questions:", len(questions_df))

# Check the categories
print("\nQuestions per category:")
print(questions_df["category"].value_counts())

# Check for missing values
print("\nMissing values:")
print(questions_df.isnull().sum())

# Verify Q006
print("\nCorrected Q006:")
display(questions_df[questions_df["id"] == "Q006"])

Total questions: 12

Questions per category:
category
Mathematics    3
Logical        3
Aptitude       3
Algorithms     3
Name: count, dtype: int64

Missing values:
id                0
category          0
difficulty        0
question          0
correct_answer    0
dtype: int64

Corrected Q006:

,id,category,difficulty,question,correct_answer
5,Q006,Logical,Hard,A three-digit code uses distinct digits. The f...,426

In [ ]:
# Store experiment results
experiment_results = []


# Run both prompting methods on every question
for _, row in questions_df.iterrows():

    question_id = row["id"]
    question = row["question"]

    for method in ["Direct", "Structured"]:

        print(f"\nQuestion: {question_id} | Method: {method}")

        try:
            result = generate_response(
                client=client,
                question=question,
                method=method
            )

            experiment_results.append({
                "id": question_id,
                "category": row["category"],
                "difficulty": row["difficulty"],
                "method": method,
                "question": question,
                "correct_answer": row["correct_answer"],
                "response": result["response"],
                "response_time_seconds": result["response_time_seconds"],
                "total_elapsed_seconds": result["total_elapsed_seconds"],
                "input_tokens": result["input_tokens"],
                "output_tokens": result["output_tokens"],
                "status": "Success"
            })

            print("Response:", result["response"])
            print("Successful request time:",
                  result["response_time_seconds"], "seconds")
            print("Total elapsed time:",
                  result["total_elapsed_seconds"], "seconds")
            print("Output tokens:", result["output_tokens"])

        except Exception as error:

            print("Request failed:", error)

            experiment_results.append({
                "id": question_id,
                "category": row["category"],
                "difficulty": row["difficulty"],
                "method": method,
                "question": question,
                "correct_answer": row["correct_answer"],
                "response": "",
                "response_time_seconds": None,
                "total_elapsed_seconds": None,
                "input_tokens": None,
                "output_tokens": None,
                "status": "Failed"
            })

# Convert results to a DataFrame
results_df = pd.DataFrame(experiment_results)

print("\nExperiment run finished!")
print("Total recorded attempts:", len(results_df))
print("Successful responses:", (results_df["status"] == "Success").sum())
print("Failed responses:", (results_df["status"] == "Failed").sum())

display(results_df.head())

Question: Q001 | Method: Direct
Response: 30
Successful request time: 3.763 seconds
Total elapsed time: 3.763 seconds
Output tokens: 2

Question: Q001 | Method: Structured
Response: Here is the step-by-step solution to the problem:

### **Step 1: Understand the terms and convert the percentage**
* "Percent" means "per one hundred."
* Convert $15\%$ into a fraction or a decimal:
  $$\text{Fraction: } \frac{15}{100}$$
  $$\text{Decimal: } 0.15$$

---

### **Step 2: Perform the calculation**
To find $15\%$ of $200$, multiply the converted percentage by $200$:

* **Using fractions:**
  $$\frac{15}{100} \times 200 = 15 \times \frac{200}{100} = 15 \times 2 = 30$$

* **Using decimals:**
  $$0.15 \times 200 = 30$$

---

### **Step 3: Check the result**
We can check the answer using mental benchmark percentages:
* $10\%$ of $200 = 20$
* $5\%$ of $200 = 10$ (half of $10\%$)
* $15\% = 10\% + 5\% = 20 + 10 = 30$

The calculation is confirmed to be correct.

---

### **Final Answer:**
$15$ percent of $200$ is **$30$**.
Successful request time: 14.732 seconds
Total elapsed time: 14.732 seconds
Output tokens: 327

Question: Q002 | Method: Direct
Response: 25%
Successful request time: 2.11 seconds
Total elapsed time: 2.11 seconds
Output tokens: 3

Question: Q002 | Method: Structured
Response: Here is the step-by-step solution to the problem:

### **Step 1: Identify the given values**
* **Cost Price (CP):** $800\text{ rupees}$
* **Selling Price (SP):** $1000\text{ rupees}$

---

### **Step 2: Calculate the profit**
Profit is calculated by subtracting the Cost Price from the Selling Price:
$$\text{Profit} = \text{Selling Price} - \text{Cost Price}$$
$$\text{Profit} = 1000 - 800 = 200\text{ rupees}$$

---

### **Step 3: Calculate the profit percentage**
The formula for profit percentage is:
$$\text{Profit Percentage} = \left(\frac{\text{Profit}}{\text{Cost Price}}\right) \times 100$$

Substitute the values into the formula:
$$\text{Profit Percentage} = \left(\frac{200}{800}\right) \times 100$$
$$\text{Profit Percentage} = \left(\frac{1}{4}\right) \times 100 = 25\%$$

---

### **Step 4: Check the result**
* $25\%$ of the Cost Price ($800\text{ rupees}$) is:
  $$0.25 \times 800 = 200\text{ rupees}$$
* Adding this profit to the Cost Price gives the Selling Price:
  $$800 + 200 = 1000\text{ rupees}$$

The calculation is verified and correct.

---

### **Final Answer**
The profit percentage is **$25\%$**.
Successful request time: 4.167 seconds
Total elapsed time: 4.167 seconds
Output tokens: 378

Question: Q003 | Method: Direct
Response: 4 percent decrease (or -4%)
Successful request time: 2.271 seconds
Total elapsed time: 2.271 seconds
Output tokens: 8

Question: Q003 | Method: Structured
Response: To solve this problem, we will follow a structured approach.

---

### **Step 1: Choose an Initial Value**
Let the original number be $100$ (using $100$ makes percentage calculations straightforward).

---

### **Step 2: Apply the First Change (20% Increase)**
* Increase = $20\% \text{ of } 100 = 0.20 \times 100 = 20$
* New Value after increase = $100 + 20 = 120$

---

### **Step 3: Apply the Second Change (20% Decrease)**
The 20% decrease applies to the **new** value ($120$), not the original number.
* Decrease = $20\% \text{ of } 120 = 0.20 \times 120 = 24$
* Final Value after decrease = $120 - 24 = 96$

---

### **Step 4: Calculate the Overall Percentage Change**
* Absolute Change = $\text{Final Value} - \text{Initial Value} = 96 - 100 = -4$
* Percentage Change = $\left(\frac{\text{Change}}{\text{Initial Value}}\right) \times 100 = \left(\frac{-4}{100}\right) \times 100 = -4\%$

The negative sign indicates a decrease.

---

### **Step 5: Verification using Multipliers (Algebraic Method)**
Let the original number be $x$.
1. Increasing by $20\%$ multiplies $x$ by $(1 + 0.20) = 1.20$.
2. Decreasing by $20\%$ multiplies the result by $(1 - 0.20) = 0.80$.

$$\text{Final Value} = x \times 1.20 \times 0.80 = 0.96x$$

$$\text{Overall Change} = \frac{0.96x - x}{x} \times 100\% = -0.04 \times 100\% = -4\%$$

Both methods yield the same result.

---

### **Final Answer**
The overall percentage change is a **decrease of 4%** (or **$-4\%$**).
Successful request time: 4.524 seconds
Total elapsed time: 4.524 seconds
Output tokens: 528

Question: Q004 | Method: Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Response: C
Successful request time: 2.877 seconds
Total elapsed time: 18.122 seconds
Output tokens: 1

Question: Q004 | Method: Structured
Response: Here is the step-by-step solution to the problem:

### **Step 1: Identify the given information**
* Relationship 1: $A$ is taller than $B$ ($A > B$).
* Relationship 2: $B$ is taller than $C$ ($B > C$).

---

### **Step 2: Combine the relationships**
Using the transitive property of height comparisons:
* Since $A > B$ and $B > C$, we can combine these into a single ordering from tallest to shortest:
  $$\text{Height: } A > B > C$$

---

### **Step 3: Analyze the order**
* **Tallest:** $A$
* **Middle:** $B$
* **Shortest:** $C$

---

### **Step 4: Check the result**
* Is $A$ taller than $B$? Yes.
* Is $B$ taller than $C$? Yes.
* There is no one shorter than $C$.

---

### **Final Answer:**
**C** is the shortest.
Successful request time: 6.371 seconds
Total elapsed time: 6.371 seconds
Output tokens: 233

Question: Q005 | Method: Direct
Response: No
Successful request time: 6.279 seconds
Total elapsed time: 6.279 seconds
Output tokens: 1

Question: Q005 | Method: Structured
Response: To solve this question, we can use a structured deductive reasoning approach (categorical syllogism).

### **Step 1: Identify the Given Premises**
1. **Premise 1:** All roses are flowers.
   * In set notation: $\text{Roses} \subseteq \text{Flowers}$
2. **Premise 2:** No flowers are made of metal.
   * In set notation: $\text{Flowers} \cap \text{Made of metal} = \emptyset$

---

### **Step 2: Perform the Logical Reasoning**
* Let $x$ be any rose.
* According to **Premise 1**, because $x$ is a rose, $x$ must be a flower ($x \in \text{Flowers}$).
* According to **Premise 2**, anything that is a flower cannot be made of metal ($x \notin \text{Made of metal}$).
* By the transitive property of inclusion, since the entire set of roses is contained within the set of flowers, and none of the set of flowers can be made of metal, no member of the set of roses can be made of metal.

---

### **Step 3: Check the Result**
* This forms a standard classical syllogism of the form *Celarent*:
  * **Major Premise:** No $M$ (flowers) are $P$ (made of metal).
  * **Minor Premise:** All $S$ (roses) are $M$ (flowers).
  * **Conclusion:** No $S$ (roses) are $P$ (made of metal).
* The conclusion logically and necessarily follows from the premises without contradiction.

---

### **Final Answer**
**No**, according to the statements, no rose can be made of metal.
Successful request time: 5.647 seconds
Total elapsed time: 5.647 seconds
Output tokens: 382

Question: Q006 | Method: Direct
Response: 426
Successful request time: 2.621 seconds
Total elapsed time: 2.621 seconds
Output tokens: 3

Question: Q006 | Method: Structured
Response: To solve the question, we follow a structured step-by-step approach:

### **Step 1: Identify the given information**
Let the three-digit code be represented as $d_1 d_2 d_3$, where:
- $d_1$ is the first digit
- $d_2$ is the second digit
- $d_3$ is the third digit

We are given:
1. The second digit is $2$ ($d_2 = 2$).
2. The first digit is twice the second digit ($d_1 = 2 \times d_2$).
3. The third digit is the sum of the first two digits ($d_3 = d_1 + d_2$).
4. All digits must be distinct.

---

### **Step 2: Calculate each digit**
1. **Second digit ($d_2$):**
   $$d_2 = 2$$

2. **First digit ($d_1$):**
   $$d_1 = 2 \times 2 = 4$$

3. **Third digit ($d_3$):**
   $$d_3 = d_1 + d_2 = 4 + 2 = 6$$

---

### **Step 3: Check the conditions**
- **First digit is twice the second:** $4 = 2 \times 2$ (True)
- **Third digit is the sum of the first two:** $6 = 4 + 2$ (True)
- **Digits are distinct:** The digits are $4$, $2$, and $6$, which are all different (True)
- **Valid digits:** $4$, $2$, and $6$ are single digits between $0$ and $9$ (True)

---

### **Final Answer:**
The code is **426**.
Successful request time: 5.452 seconds
Total elapsed time: 5.452 seconds
Output tokens: 405

Question: Q007 | Method: Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Request failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 58.609307911s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '58s'}]}}

Question: Q007 | Method: Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Response: Here is the step-by-step solution to the problem:

### **Step 1: Identify the given information**
* **Distance ($d$):** $150\text{ km}$
* **Time ($t$):** $3\text{ hours}$

---

### **Step 2: Identify the formula**
The formula for speed ($v$) when traveling at a constant rate is:
$$\text{Speed} = \frac{\text{Distance}}{\text{Time}}$$

---

### **Step 3: Perform the calculation**
Substitute the given values into the formula:
$$\text{Speed} = \frac{150\text{ km}}{3\text{ hours}} = 50\text{ km/h}$$

---

### **Step 4: Check the result**
To verify, multiply the calculated speed by the time:
$$\text{Distance} = 50\text{ km/h} \times 3\text{ hours} = 150\text{ km}$$
The result matches the original distance given in the problem.

---

### **Final Answer**
The vehicle's speed is **$50\text{ km/h}$** (kilometers per hour).
Successful request time: 4.175 seconds
Total elapsed time: 19.341 seconds
Output tokens: 269

Question: Q008 | Method: Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Request failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\nPlease retry in 17h49m23.326158038s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '64163s'}]}}

Question: Q008 | Method: Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Request failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\nPlease retry in 17h49m7.619362234s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '64147s'}]}}

Question: Q009 | Method: Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Request failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\nPlease retry in 17h48m51.642844345s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '64131s'}]}}

Question: Q009 | Method: Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Request failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\nPlease retry in 17h48m35.597532579s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '64115s'}]}}

Question: Q010 | Method: Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Request failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\nPlease retry in 17h48m19.966423669s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '64099s'}]}}

Question: Q010 | Method: Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Request failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\nPlease retry in 17h48m3.97692791s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '64083s'}]}}

Question: Q011 | Method: Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...

,id,category,difficulty,method,question,correct_answer,response,response_time_seconds,total_elapsed_seconds,input_tokens,output_tokens,status
0,Q001,Mathematics,Easy,Direct,What is 15 percent of 200?,30,30,3.763,3.763,30.0,2.0,Success
1,Q001,Mathematics,Easy,Structured,What is 15 percent of 200?,30,Here is the step-by-step solution to the probl...,14.732,14.732,53.0,327.0,Success
2,Q002,Mathematics,Medium,Direct,An item costs 800 rupees and sells for 1000 ru...,25%,25%,2.110,2.110,41.0,3.0,Success
3,Q002,Mathematics,Medium,Structured,An item costs 800 rupees and sells for 1000 ru...,25%,Here is the step-by-step solution to the probl...,4.167,4.167,64.0,378.0,Success
4,Q003,Mathematics,Hard,Direct,A number is increased by 20 percent and then d...,4% decrease,4 percent decrease (or -4%),2.271,2.271,43.0,8.0,Success

In [21]:
print("Total rows:", len(results_df))

print("\nResults by method and status:")
display(
    results_df.groupby(["method", "status"]).size().unstack(fill_value=0)
)

print("\nFailed requests:")
display(
    results_df.loc[
        results_df["status"] == "Failed",
        ["id", "method", "response"]
    ]
)

Total rows: 24

Results by method and status:

status      Failed  Success
method
Direct           6        6
Structured       5        7

Failed requests:

      id      method response
12  Q007      Direct
14  Q008      Direct
15  Q008  Structured
16  Q009      Direct
17  Q009  Structured
18  Q010      Direct
19  Q010  Structured
20  Q011      Direct
21  Q011  Structured
22  Q012      Direct
23  Q012  Structured

In [22]:
results_path = project_dir / "results" / "results_partial.csv"

results_df.to_csv(results_path, index=False)

print("Partial results saved to:")
print(results_path)

Partial results saved to:
C:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\results\results_partial.csv

In [23]:
import time
import pandas as pd

# Keep a copy of the existing results
recovered_results = results_df.copy()

# Identify the failed requests
failed_requests = recovered_results[
    recovered_results["status"] == "Failed"
].copy()

print("Failed requests to retry:", len(failed_requests))

# Retry only failed requests
for index, row in failed_requests.iterrows():

    print(f"\nRetrying {row['id']} | {row['method']}")

    try:
        result = generate_response(
            client=client,
            question=row["question"],
            method=row["method"]
        )

        # Update the existing row with the new response
        recovered_results.loc[index, "response"] = result["response"]
        recovered_results.loc[index, "response_time_seconds"] = (
            result["response_time_seconds"]
        )
        recovered_results.loc[index, "total_elapsed_seconds"] = (
            result["total_elapsed_seconds"]
        )
        recovered_results.loc[index, "input_tokens"] = result["input_tokens"]
        recovered_results.loc[index, "output_tokens"] = result["output_tokens"]
        recovered_results.loc[index, "status"] = "Success"

        print("Retry successful!")
        print("Response:", result["response"])

    except Exception as error:

        # Keep the request marked as failed and display the actual error
        recovered_results.loc[index, "response"] = ""
        recovered_results.loc[index, "status"] = "Failed"

        print("Retry failed.")
        print("Error:", repr(error))

    # Short pause between requests
    time.sleep(3)

    # Save progress after every request
    results_path = project_dir / "results" / "results.csv"
    recovered_results.to_csv(results_path, index=False)

# Replace the old DataFrame with the recovered results
results_df = recovered_results

print("\nRecovery attempt completed.")
print("Successful:", (results_df["status"] == "Success").sum())
print("Failed:", (results_df["status"] == "Failed").sum())
print("Saved to:", results_path)

Failed requests to retry: 11

Retrying Q007 | Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h33m45.504150759s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63225s'}]}}")

Retrying Q008 | Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h33m26.033625123s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63206s'}]}}")

Retrying Q008 | Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h33m7.280788088s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63187s'}]}}")

Retrying Q009 | Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h32m48.64393425s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63168s'}]}}")

Retrying Q009 | Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h32m29.995177077s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63149s'}]}}")

Retrying Q010 | Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h32m11.3068456s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63131s'}]}}")

Retrying Q010 | Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h31m52.247412995s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63112s'}]}}")

Retrying Q011 | Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h31m33.655956859s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63093s'}]}}")

Retrying Q011 | Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h31m15.001843237s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63075s'}]}}")

Retrying Q012 | Direct
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h30m56.244883952s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63056s'}]}}")

Retrying Q012 | Structured
Temporary API error. Retrying in 2 seconds (attempt 1/4)...
Temporary API error. Retrying in 4 seconds (attempt 2/4)...
Temporary API error. Retrying in 8 seconds (attempt 3/4)...
Retry failed.
Error: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.8-flash\\nPlease retry in 17h30m37.373700435s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '63037s'}]}}")

Recovery attempt completed.
Successful: 13
Failed: 11
Saved to: C:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\results\results.csv

In [24]:
results_path = project_dir / "results" / "results_partial.csv"

results_df.to_csv(results_path, index=False)

print("Results backed up successfully!")
print("Successful responses:", (results_df["status"] == "Success").sum())
print("Failed responses:", (results_df["status"] == "Failed").sum())
print("Saved to:", results_path)

Results backed up successfully!
Successful responses: 13
Failed responses: 11
Saved to: C:\Users\jhabh\OneDrive\Desktop\LLM_Reasoning_Experiment\results\results_partial.csv